name: CI

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code
                uses: actions/Checkout@v4 
            
            -   name: Checkout Code and Setup Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'

            -   name: Install Requirements
                run: |
                    python3 -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run Pytest
                run: pytest -q
